### ISSUE TITLE
Connection lost and not reconnecting

### ISSUE THREAD

**Issue by oyvindwe** [thomasloven/hass_plejd#19]
After every few days, I loose connection to the mesh, and it fails to reconnect. Whenever this happens, I need to restart HA to reconnect. I am happy to help out debugging, but I'm not sure where to start.

Home Assistant 2023.1.2 (but this problem has been since i started using the integration).

```
2023-01-10 23:23:41.196 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/esphome/bluetooth/client.py", line 96, in _async_wrap_bluetooth_operation
    return await func(self, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/esphome/bluetooth/client.py", line 540, in write_gatt_char
    await self._client.bluetooth_gatt_write(
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/client.py", line 667, in bluetooth_gatt_write
    await self._send_bluetooth_message_await_response(
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/client.py", line 440, in _send_bluetooth_message_await_response
    raise BluetoothGATTAPIError(BluetoothGATTError.from_pb(resp[0]))
aioesphomeapi.core.BluetoothGATTAPIError: Bluetooth GATT Error address=DE:B2:68:ED:E5:0D handle=40 error=-1 description=Not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/plejd/__init__.py", line 98, in _ping
    if not await plejdManager.keepalive():
  File "/config/custom_components/plejd/pyplejd/__init__.py", line 75, in keepalive
    retval = await self.mesh.ping()
  File "/config/custom_components/plejd/pyplejd/mesh.py", line 159, in ping
    return await self._ping()
  File "/config/custom_components/plejd/pyplejd/mesh.py", line 167, in _ping
    await self.client.write_gatt_char(PLEJD_PING, ping, response=True)
  File "/usr/local/lib/python3.10/site-packages/bleak/__init__.py", line 593, in write_gatt_char
    await self._backend.write_gatt_char(char_specifier, data, response)
  File "/usr/src/homeassistant/homeassistant/components/esphome/bluetooth/client.py", line 79, in _async_wrap_bluetooth_connected_operation
    await task
  File "/usr/src/homeassistant/homeassistant/components/esphome/bluetooth/client.py", line 117, in _async_wrap_bluetooth_operation
    self._async_ble_device_disconnected()
  File "/usr/src/homeassistant/homeassistant/components/esphome/bluetooth/client.py", line 197, in _async_ble_device_disconnected
    self._async_disconnected_cleanup()
  File "/usr/src/homeassistant/homeassistant/components/esphome/bluetooth/client.py", line 192, in _async_disconnected_cleanup
    self._unsubscribe_connection_state()
  File "/usr/src/homeassistant/homeassistant/components/esphome/bluetooth/client.py", line 168, in _unsubscribe_connection_state
    self._cancel_connection_state()
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/client.py", line 534, in unsub
    self._connection.remove_message_callback(on_msg, msg_types)
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/connection.py", line 455, in remove_message_callback
    self._message_handlers[msg_type].remove(on_message)
KeyError: <class 'api_pb2.BluetoothDeviceConnectionResponse'>
```

**Comment by martin-oom** [comment]
Make sure you are not also using the Plejd app. If I recall correctly there can only be one active "controller" in a plejd network (eg this integration OR the plejd app). After I unistalled the plejd app this plugin has been running flawlessly for several months.

**Comment by oyvindwe** [comment]
At least only one controller can be connected to one puck/smart plug at a time. I'll see if opening up the app forces the disconnect, but HA should be able to reconnect.

**Comment by oyvindwe** [comment]
> Make sure you are not also using the Plejd app.

@martin-oom Tested now; I am connected with both HA and the iPhone app, and I can turn on and off switches both places, and status is reflected in both places as well. So I don't think it's a problem with multiple controllers (except if they try to connect to the same device in the mesh).

**Comment by Minglarn** [comment]
Hi! Looks like the PLEJD integration doesnt work with the BT Low Energy Monitor system?
My plejd devices vanished when switching over to "Passive BLE monitor"... Any clues?

**Comment by ricmik** [comment]
> Hi! Looks like the PLEJD integration doesnt work with the BT Low Energy Monitor system?
> 
> My plejd devices vanished when switching over to "Passive BLE monitor"... Any clues?

From the BLE Monitor FAQ:

> Conflicts with other components using the same BT interface
Since our component uses a special operating mode of the HCI interface and works with a continuous data stream, conflicts with other software using the same HCI interface are possible. The conflict is caused by the fact that another component can switch the HCI interface to a different operating mode, thereby stopping the reception of data. Or our component may lead to malfunctioning of another component. A reliable, but not the only way out of this situation (apart from the refusal to use one component in favor of another) can be the use of two BT-interfaces (one for our component, the second, for example, for the tracker). Work is underway to find other solutions to such situations…

That component seems to be on its way to being replaced by home assistant core in the future.

**Comment by oyvindwe** [comment]
@Minglarn Good that you solved your problem! But please don't go off topic in existing issues.

**Comment by oyvindwe** [comment]
I see there is a fix in HA: https://github.com/home-assistant/core/pull/90014

I'll test if this also fixes this issue.

**Comment by oyvindwe** [comment]
Unfortunately the error still occurs with HA 2023.3.6

@thomasloven Are you able to see from the stack trace if this is a problem with pyplejd, esphome/bluetooth, or the combination? I'm happy to try to debug, but I'm still a bit lost on where to start.

**Comment by thomasloven** [comment]
Please try the latest version. There's been a lot of changes.

Also, if you are using an esphome bluetooth relay, make sure that's updated. There's been some fantastic improvements the last couple of months.

**Comment by oyvindwe** [comment]
Yes, I've noted a lot of progress on bt support in HA. :)

I am on latest version HA, ESPHome bt proxy, and hass_plejd. It does seem more stable now, but I've also been restarting a lot for other reasons, so can't really say if this is fixed or not yet. I'll follow up after a stable period!

**Comment by oyvindwe** [comment]
Looks like it reconnects properly now. I see 3 of these in the logs, but HA has managed to reconnect:

```
2023-08-04 17:26:23.060 WARNING (MainThread) [pyplejd.mesh] Error connecting to Plejd device: plejd - <address redacted>: Failed to connect after 9 attempt(s): No backend with an available connection slot that can reach address <address redacted> was found: The proxy/adapter is out of connection slots or the device is no longer reachable; Add additional proxies (https://esphome.github.io/bluetooth-proxies/) near this device
```

I don't see the original error message anymore.

I have not moved anything around or used the Plejd app, so I'm not sure why I get these warnings, but as long as HA reconnects within reasonable time I'm happy. :)

Closing this issue.
