### ISSUE TITLE
Plejd integration not loaded anymore

### ISSUE THREAD

**Issue by pissten** [thomasloven/hass_plejd#42]
Suddenly plejd integration stopped working. Tried to reconfigure and reload, but integration fails to load.
Upgraded to latest HA version today, and still got the same error.

`Denne feilen stammer fra en tilpasset integrasjon.

Logger: homeassistant.config_entries
Source: custom_components/plejd/__init__.py:29
Integration: Plejd (documentation)
First occurred: 18:37:31 (2 occurrences)
Last logged: 18:43:58

Error setting up entry xxxx for plejd
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/plejd/__init__.py", line 29, in async_setup_entry
    await plejdManager.init()
  File "/usr/local/lib/python3.11/site-packages/pyplejd/__init__.py", line 40, in init
    await self.cloud.load_site_details()
  File "/usr/local/lib/python3.11/site-packages/pyplejd/cloud/__init__.py", line 74, in load_site_details
    await self.get_details()
  File "/usr/local/lib/python3.11/site-packages/pyplejd/cloud/__init__.py", line 63, in get_details
    await _set_session_token(session, self.username, self.password)
  File "/usr/local/lib/python3.11/site-packages/pyplejd/cloud/__init__.py", line 26, in _set_session_token
    resp = await session.post(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 643, in _request
    resp.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://cloud.plejd.com/parse/login')
`
![image](https://github.com/thomasloven/hass_plejd/assets/16886605/b86a79b9-4829-4e35-9f6c-16de1616bd03)

**Comment by thomasloven** [comment]
For information, this is related ti #37
